version: '2'
services:
    httpbin:
      build:
        context: '.'
        dockerfile: Dockerfile.alpine
      image: httpbin:alpine
      ports:
        - '8080:80'
      environment:
        - "GUNICORN_CMD_ARGS=--capture-output --error-logfile - --access-logfile - --access-logformat '%(h)s %(t)s %(r)s %(s)s Host: %({Host}i)s}'"
