services:
    httpbin:
      build:
        context: '.'
        dockerfile: Dockerfile.alpine
        # uncomment to fetch your custom certs for build the image
        #args:
        #  - CA_CERT_URL=http://your-host-serving-certs/ca-certs-bundle.crt
      image: httpbin:alpine
      ports:
        - '8081:80'
      environment:
        - "GUNICORN_CMD_ARGS=--capture-output --error-logfile - --access-logfile - --access-logformat '%(h)s %(t)s %(r)s %(s)s Host: %({Host}i)s}'"
